### ISSUE TITLE
Wrong denominator

### ISSUE THREAD

**Issue by wenig** [Tarzanagh/DADAM#1]
https://github.com/Tarzanagh/DADAM/blob/eced8a1d278e9359984db34e5d2a8499ef82946f/DADAM-master/dadam_algorithms_main/dadam.m#L108

Shouldn't the denominator include **v_bar_node{ii}** instead of **v_hat_node{ii}**? As I understand it, your v_bar_node{ii} is the "v_hat" from Algorithm 1 in your paper.

**Comment by Tarzanagh** [comment]
Thank you for your comment. Modified and Fixed!
